packages:
  - name: ikun-react
    source:
      url: https://github.com/ikun-kit/react
      packagesDir: packages
    target: ./src/components
    description: ikun-kit React component library
  - name: shadcn-ui
    source:
      url: https://github.com/shadcn-ui/ui
      packagesDir: apps/www/registry/default/ui
    target: ./src/ui
    description: shadcn/ui component library
